version: "3"

services:
  db:
    image: mysql:5.7
    container_name: mywebapp_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mywebapp
      MYSQL_PASSWORD: mywebapp123
      MYSQL_DATABASE: mydb
    ports:
      - "32000:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --p $$MYSQL_PASSWORD

  npm:
    image: node
    container_name: mywebapp_npm
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run watch"

  flask:
    build: .
    container_name: mywebapp_flask
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    depends_on:
      - db
    working_dir: /app
    command: python -m flaskapp

volumes:
  dbdata:
