version: "3"

services:
  db:
    image: mysql:5.7
    container_name: mywebapp_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mywebapp
      MYSQL_PASSWORD: mywebapp123
    ports:
      - "32000:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  npm:
    image: node
    container_name: mywebapp_npm
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run watch"

  flask:
    build: .
    container_name: mywebapp_flask
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    links: db
    working_dir: /app
    command: python -m flaskapp

